FROM node:18.2@sha256:40ff814f32ba880e4320c9e690a8cda008373085e5ec9d4ca5166582ac9eb34b

EXPOSE 80

WORKDIR /usr/src/something-shop

RUN mkdir src
# Coppy the monorepos source code
COPY . src

WORKDIR /usr/src/something-shop/src

RUN ls -laf

RUN npm i

RUN npx nx build something-shop --configuration=production

FROM nginx:1.21@sha256:b495f952df67472c3598b260f4b2e2ba9b5a8b0af837575cf4369c95c8d8a215

COPY --from=0 /usr/src/something-shop/src/dist/apps/something-shop ./usr/share/nginx/html

RUN rm -rf src

