ARG ROCKET_ADDRESS=0.0.0.0
ARG DATABASE_URL
ARG AUTH_SECRET
FROM amd64/rust:1.62.10@sha256:4f1d43c216d995c2f734d7c682bc3e2abe3e110961cda4ae0743ce3944e673a2  as builder

WORKDIR /usr/src/something
COPY . .

EXPOSE 80

RUN cargo build --release

FROM debian:buster-slim

COPY --from=builder /usr/src/something/target/release/something /bin
COPY --from=builder /usr/src/something/apps/something/rocket.toml /usr

RUN apt-get update && apt-get install -y libssl-dev libmariadb-dev && rm -rf /var/lib/apt/lists/*

ENV AUTH_SECRET=${AUTH_SECRET}
ENV ROCKET_ADDRESS=${ROCKET_ADDRESS}
ENV DATABASE_URL=${DATABASE_URL}
ENV ROCKET_CONFIG=/usr/rocket.toml

CMD ["something"]