FROM rust:1.62.10@sha256:4f1d43c216d995c2f734d7c682bc3e2abe3e110961cda4ae0743ce3944e673a2

WORKDIR /usr/src/something
COPY . .

EXPOSE 80

ENV ROCKET_CONFIG=/usr/src/something/rocket.toml

RUN cargo build --release 

CMD ["target/release/something "]