FROM amd64/rust:1.62.10@sha256:4f1d43c216d995c2f734d7c682bc3e2abe3e110961cda4ae0743ce3944e673a2  as builder

WORKDIR /usr/src/something
COPY . .

EXPOSE 80

ENV ROCKET_CONFIG=/usr/src/something/rocket.toml

RUN cargo build --release

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libssl-dev libmariadb-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/something/target/release/something /bin
RUN export ROCKET_ADDRESS=0.0.0.0
CMD ["something"]