name: commit-checks
on: [push]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  commit-checks:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [commit-checks]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --configuration=production
      - run: npx nx affected --target=test --parallel
      # - run: npx nx affected --target=lint --parallel
      - run: npx nx-cloud stop-all-agents
      - run: export NX_CLOUD_DISTRIBUTED_EXECUTION=false && npx nx affected --target=build-storybook --parallel --configuration=ci

  agents:
    runs-on: ubuntu-latest
    name: build test lint
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
