name: Version

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: cargo install cargo-edit
      - run: npx nx affected --target version --baseBranch main --parallel false --base=last-release
      - name: Tag last-release
        run: |
          git tag -f last-release
          git push origin last-release --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
